# Generated by Django 4.2.5 on 2023-09-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0002_alter_transactions_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
